import Head from "next/head";
import { useRouter } from "next/router";
import { useState } from "react";
import { api } from "../services/api";

export default function Home() {
  const { push } = useRouter();

  const [name, setName] = useState<string>();
  const [room, setRoom] = useState<string>();

  async function onCreate() {
    if (!name) {
      alert("Who are you ?");
      return;
    }

    const { id } = await api.post("rooms", { name });

    push(`rooms/${id}/users/${name}/create`);
  }

  function onJoin(e: React.FormEvent) {
    e.preventDefault();

    if (!name) {
      alert("Who are you ?");
      return;
    }
    if (!room) {
      alert("Where do you wanna go?");
      return;
    }

    push(`rooms/${room}/users/${name}/join`);
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <section>
          <div className="flex justify-center content-center mt-40">
            <h1 className="text-3xl font-bold">AmongOld!</h1>
          </div>
        </section>
        <section>
          <div className="flex justify-center content-center mt-40">
            <form onSubmit={onJoin}>
              <label className="label">
                <span className="label-text">What is your name?</span>
                <span className="label-text-alt">Be Creative</span>
              </label>
              <input
                type="text"
                placeholder="Name"
                className="input input-bordered w-full max-w-xs"
                onChange={(e) => setName(e.target.value)}
              />
              <label className="label">
                <span className="label-text">Joining a room?</span>
                <span className="label-text-alt">Ask to the owner</span>
              </label>
              <input
                type="text"
                placeholder="Code"
                className="input input-bordered w-full max-w-xs"
                onChange={(e) => setRoom(e.target.value)}
              />
              <div className="flex justify-around content-center mt-8">
                <button type="submit" className="btn btn-primary w-40">
                  Join
                </button>
                <button
                  onClick={onCreate}
                  className="btn btn-outline btn-primary w-40"
                >
                  Create
                </button>
              </div>
            </form>
          </div>
        </section>
      </main>
    </>
  );
}
