import Head from "next/head";
import { useRouter } from "next/router";
import { useState } from "react";

export default function Home() {
  const { push } = useRouter();

  const [name, setName] = useState<string>();
  const [room, setRoom] = useState<string>();

  function onCreate() {
    if (!name) {
      alert("Who are you ?");
      return;
    }
    push("rooms", { query: { name } });
  }

  function onJoin(e: React.FormEvent) {
    e.preventDefault();

    if (!name) {
      alert("Who are you ?");
      return;
    }
    if (!room) {
      alert("Where do you wanna go?");
      return;
    }

    push(`rooms/${room}/users/${name}`);
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <section>
          <div className="flex justify-center content-center mt-40">
            <h1 className="text-3xl font-bold">AmongOld!</h1>
          </div>
        </section>
        <section>
          <div className="flex justify-center content-center mt-40">
            <form onSubmit={onJoin}>
              <div className="flex justify-center content-center">
                <input
                  placeholder="Name"
                  className="text-center"
                  onChange={(e) => setName(e.target.value)}
                />
                <input
                  placeholder="Code"
                  className="text-center"
                  onChange={(e) => setRoom(e.target.value)}
                />
              </div>
              <div className="flex justify-center content-center mt-8">
                <button type="submit">Join</button>
              </div>
            </form>
          </div>
        </section>
        <section>
          <div className="flex justify-center content-center mt-8">
            <button onClick={onCreate}>Create</button>
          </div>
        </section>
      </main>
    </>
  );
}
